# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: slave
  apiServerPort: 6443
nodes:
- role: control-plane
- role: worker
- role: worker
